version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: miyabi-db
    environment:
      POSTGRES_USER: miyabi
      POSTGRES_PASSWORD: miyabi_dev_password
      POSTGRES_DB: miyabi_restaurant_review
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U miyabi"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: miyabi-backend
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://miyabi:miyabi_dev_password@postgres:5432/miyabi_restaurant_review
    ports:
      - "3001:3001"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: miyabi-frontend
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:
